VERSION= '0.0.1'
APPNAME= 'fujimap'

srcdir= '.'
blddir= 'build'

def set_options(ctx):
  ctx.tool_options('compiler_cxx')
    
def configure(ctx):
  ctx.check_tool('compiler_cxx')

def build(bld):
  task1= bld(features='cxx cstaticlib',
       source       = 'fujimap.cpp fujimap_block.cpp bitvec.cpp key_edge.cpp',
       name         = 'libfujimap',
       target       = 'libfujimap',
       includes     = '.')
  task2= bld(features='cxx cprogram',
       source       = 'fujimap_main.cpp',
       target       ='fujimap',
       includes     = '.',
       uselib_local = 'libfujimap')
  bld.install_files('${PREFIX}/include', 'fujimap.hpp')